### PR TITLE
CoreSMTSolver: minor fixes

### PR DESCRIPTION
**Pull request by aehyvari**
I spotted some tiny stuff when running the CI.  I'm going to run this on the cluster.

### CODE REVIEW

**Comment by aehyvari** [comment]
Here's the plot.

### `QF_UF`

non-incremental-QF_UF-d1a5591a-2022-04-15_vs_4ad99763-2022-04-07

(updated figure)

**Comment by aehyvari** [comment]
### `QF_LRA`
non-incremental-QF_LRA-d1a5591a-2022-04-15_vs_4ad99763-2022-04-12

(updated figure)

This actually looks pretty good!

**Comment by aehyvari** [comment]
### `QF_LIA`
non-incremental-QF_LIA-d1a5591a-2022-04-15_vs_4ad99763-2022-04-13


(updated figure)
Would be great to get around this sensitivity to diverging...

**Comment by aehyvari** [comment]
### `QF_UFLRA`
non-incremental-QF_UFLRA-d1a5591a-2022-04-15_vs_4ad99763-2022-04-14

(Updated figure)

**Comment by aehyvari** [comment]
### `QF_UFLIA`

non-incremental-QF_UFLIA-d1a5591a-2022-04-17_vs_4ad99763-2022-04-14

(updated figure)

**Comment by blishko** [comment]
I think you should double-check your "master" version. I was checking the latest results I have and in QF_UFLRA, these look like the results of delayed theory combination, not the new model-based version. According to my logs, OpenSMT master should be able to solve 1262 benchmarks. Unless something has broken since February 17...

**Comment by aehyvari** [comment]
> I think you should double-check your "master" version. I was checking the latest results I have and in QF_UFLRA, these look like the results of delayed theory combination, not the new model-based version. According to my logs, OpenSMT master should be able to solve 1262 benchmarks. Unless something has broken since February 17...

I have my doubts as well.  I'll rerun the masters and update the figures accordingly.

**Comment by aehyvari** [comment]
So far the previous conclusions hold.  I'll run the difference logics so we have a complete picture.

**Comment by blishko** [comment]
I agree, can you prepare a clean branch in the main repository?

**Comment by aehyvari** [comment]
Yes, sure, no problem.

**Comment by aehyvari** [comment]
### `QF_IDL`

non-incremental-QF_IDL-d1a5591a-2022-04-19_vs_4ad99763-2022-04-14

**Comment by blishko** [comment]
Looks good! Let's include this in the main repository!

**Comment by aehyvari** [comment]
Agreed. I'm still running the QF_RDL and will then start working on the commits.

**Comment by aehyvari** [comment]
### `QF_RDL`
non-incremental-QF_RDL-d1a5591a-2022-04-25_vs_4ad99763-2022-04-25

**Pull request closed without merging**
